modLoader = "javafml"
loaderVersion = "[32,)"
license = "${license}"

[[mods]]
    modId = "${modId}"
    version = "${file.jarVersion}"
    logoFile = "${modId}.png"
    authors = "${authors}"
    displayName = "${modName}"
    description = '''${description}'''

[[dependencies.${modId}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"