modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
    modId = "phylum"
    version = "${file.jarVersion}"
    logoFile = "phylum.png"
    authors = "Spark, IcyDwarf, platypushasnohat"
    displayName = "Phylum"
    description = '''funny mod'''

[[dependencies.phylum]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.phylum]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"